steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/backend:$SHORT_SHA', './backend']

  # Step 2: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/backend:$SHORT_SHA']

  # Step 3: Deploy the image to GKE
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'set'
      - 'image'
      - 'deployment/backend'  # Change from myapp-deployment to backend
      - 'backend=gcr.io/$PROJECT_ID/backend:$SHORT_SHA'
      - '--namespace=default'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}'

images:
  - 'gcr.io/$PROJECT_ID/backend:$SHORT_SHA'

substitutions:
  _ZONE: 'us-central1-a'
  _CLUSTER_NAME: 'my-flask-cluster'

options:
  logging: CLOUD_LOGGING_ONLY
