steps:
# Step 1: Build the Docker image for the backend
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/class-activity-435807/backend:latest', '.']

# Step 2: Push the Docker image to Google Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/class-activity-435807/backend:latest']

# Step 3: Deploy the image to GKE
- name: 'gcr.io/cloud-builders/kubectl'
  args:
    - 'apply'
    - '-f'
    - 'k8s/deployment.yaml'  # Path to your Kubernetes deployment file
  env:
    - 'CLOUDSDK_COMPUTE_REGION=us-central1'  # Change to your GKE region
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'  # Change to your GKE zone
    - 'CLOUDSDK_CONTAINER_CLUSTER=my-cluster'  # Change to your GKE cluster name

# Step 4: Optional - Verify the deployment
- name: 'gcr.io/cloud-builders/kubectl'
  args:
    - 'get'
    - 'pods'

images:
  - 'gcr.io/class-activity-435807/backend:latest'  # Specifies the image to be pushed to GCR
