apiVersion: v1
kind: Service
metadata:
  name: flask-sql-service  # Name of your service
spec:
  type: LoadBalancer  # Change to ClusterIP if you only want internal access
  selector:
    app: flask-sql-deployment  # This should match the labels in your backend deployment
  ports:
    - protocol: TCP
      port: 5000  # The port you want to expose
      targetPort: 5000  # The port your Flask app is listening on
